/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.Conexao_Embalagem;
import entities.Embalagem;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luciano
 */
public class DialogEmbalagem extends javax.swing.JDialog {

    /**
     * Creates new form DialogEmbalagem
     */
    public DialogEmbalagem(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getTabelaEmbalagem();
        //teste
    }
    
    Embalagem embalagem;
    DialogAlterarEmbalagem dialogAlterarEmbalagem;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tfdDescricaoEmbalagem = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfdComprimentoEmbalagem = new javax.swing.JTextField();
        tfdLarguraEmbalagem = new javax.swing.JTextField();
        tfdAlturaEmbalagem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaEmbalagens = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        btnIncluirEmbalagem = new javax.swing.JButton();
        tfdBuscarEmbalagem = new javax.swing.JTextField();
        btnBuscarEmbalagem = new javax.swing.JButton();
        btnExcluirEmbalagem = new javax.swing.JButton();
        btnAlterarEmbalagem = new javax.swing.JButton();
        btnLimparCampos = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 650));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tfdDescricaoEmbalagem.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        tfdDescricaoEmbalagem.setForeground(new java.awt.Color(0, 0, 140));
        tfdDescricaoEmbalagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdDescricaoEmbalagemActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 140));
        jLabel5.setText("LARGURA");

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 140));
        jLabel6.setText("COMPRIMENTO");

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 140));
        jLabel7.setText("ALTURA");

        tfdComprimentoEmbalagem.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        tfdComprimentoEmbalagem.setForeground(new java.awt.Color(0, 0, 140));
        tfdComprimentoEmbalagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdComprimentoEmbalagemActionPerformed(evt);
            }
        });

        tfdLarguraEmbalagem.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        tfdLarguraEmbalagem.setForeground(new java.awt.Color(0, 0, 140));
        tfdLarguraEmbalagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdLarguraEmbalagemActionPerformed(evt);
            }
        });

        tfdAlturaEmbalagem.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        tfdAlturaEmbalagem.setForeground(new java.awt.Color(0, 0, 140));
        tfdAlturaEmbalagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdAlturaEmbalagemActionPerformed(evt);
            }
        });

        tblListaEmbalagens.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        tblListaEmbalagens.setForeground(new java.awt.Color(0, 0, 140));
        tblListaEmbalagens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", ""},
                {"", null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Descrição", "Comprimento", "Largura", "Altura"
            }
        ));
        jScrollPane1.setViewportView(tblListaEmbalagens);

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 140));
        jLabel8.setText("DESCRIÇÃO");

        btnIncluirEmbalagem.setBackground(new java.awt.Color(0, 0, 140));
        btnIncluirEmbalagem.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnIncluirEmbalagem.setForeground(new java.awt.Color(255, 255, 255));
        btnIncluirEmbalagem.setText("Incluir Embalagem");
        btnIncluirEmbalagem.setBorder(null);
        btnIncluirEmbalagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirEmbalagemActionPerformed(evt);
            }
        });

        tfdBuscarEmbalagem.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        tfdBuscarEmbalagem.setForeground(new java.awt.Color(0, 0, 140));
        tfdBuscarEmbalagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdBuscarEmbalagemActionPerformed(evt);
            }
        });

        btnBuscarEmbalagem.setBackground(new java.awt.Color(0, 0, 140));
        btnBuscarEmbalagem.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnBuscarEmbalagem.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarEmbalagem.setText("Buscar Embalagens");
        btnBuscarEmbalagem.setBorder(null);
        btnBuscarEmbalagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEmbalagemActionPerformed(evt);
            }
        });

        btnExcluirEmbalagem.setBackground(new java.awt.Color(0, 0, 140));
        btnExcluirEmbalagem.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnExcluirEmbalagem.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluirEmbalagem.setText("Excluir Embalagem");
        btnExcluirEmbalagem.setBorder(null);
        btnExcluirEmbalagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirEmbalagemActionPerformed(evt);
            }
        });

        btnAlterarEmbalagem.setBackground(new java.awt.Color(0, 0, 140));
        btnAlterarEmbalagem.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnAlterarEmbalagem.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterarEmbalagem.setText("Alterar Embalagem");
        btnAlterarEmbalagem.setBorder(null);
        btnAlterarEmbalagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarEmbalagemActionPerformed(evt);
            }
        });

        btnLimparCampos.setBackground(new java.awt.Color(0, 0, 140));
        btnLimparCampos.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnLimparCampos.setForeground(new java.awt.Color(255, 255, 255));
        btnLimparCampos.setText("Limpar Campos");
        btnLimparCampos.setBorder(null);
        btnLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCamposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(tfdBuscarEmbalagem, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnBuscarEmbalagem, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel8))
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel7)))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfdDescricaoEmbalagem, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfdComprimentoEmbalagem, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfdLarguraEmbalagem, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfdAlturaEmbalagem, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnLimparCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnIncluirEmbalagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(btnAlterarEmbalagem, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnExcluirEmbalagem, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 160, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfdBuscarEmbalagem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarEmbalagem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel6)
                                .addGap(23, 23, 23)
                                .addComponent(jLabel5)
                                .addGap(23, 23, 23)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfdDescricaoEmbalagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(tfdComprimentoEmbalagem, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(tfdLarguraEmbalagem, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(tfdAlturaEmbalagem, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(btnIncluirEmbalagem, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimparCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExcluirEmbalagem, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterarEmbalagem, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel5.setBackground(new java.awt.Color(0, 0, 140));

        jLabel1.setBackground(new java.awt.Color(0, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LOGO ERS");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(854, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(0, 0, 140));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("© ECOMMERCE REGISTER SOLUTIONS - TODOS OS DIREITOS RESERVADOS © ");
        jPanel4.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfdDescricaoEmbalagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdDescricaoEmbalagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdDescricaoEmbalagemActionPerformed

    private void tfdComprimentoEmbalagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdComprimentoEmbalagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdComprimentoEmbalagemActionPerformed

    private void tfdLarguraEmbalagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdLarguraEmbalagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdLarguraEmbalagemActionPerformed

    private void tfdAlturaEmbalagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdAlturaEmbalagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdAlturaEmbalagemActionPerformed

    private void btnIncluirEmbalagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirEmbalagemActionPerformed
        Conexao_Embalagem conexao_Embalagem = new Conexao_Embalagem();
        
        embalagem = new Embalagem();
        
        embalagem.setDescricao(tfdDescricaoEmbalagem.getText());
        embalagem.setComprimento(Double.parseDouble(tfdComprimentoEmbalagem.getText()));
        embalagem.setLargura(Double.parseDouble(tfdLarguraEmbalagem.getText()));
        embalagem.setAltura(Double.parseDouble(tfdAlturaEmbalagem.getText()));
        
        conexao_Embalagem.inserir(embalagem);
        getTabelaEmbalagem();;
        
        JOptionPane.showMessageDialog(null, "Embalagem cadastrada com sucesso!");
        
    }//GEN-LAST:event_btnIncluirEmbalagemActionPerformed

    private void tfdBuscarEmbalagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdBuscarEmbalagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdBuscarEmbalagemActionPerformed

    private void btnBuscarEmbalagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEmbalagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarEmbalagemActionPerformed

    private void btnExcluirEmbalagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirEmbalagemActionPerformed
        Conexao_Embalagem conexao_Embalagem = new Conexao_Embalagem();
        
        int embalagemSelecionada = tblListaEmbalagens.getSelectedRow();
        
        if (embalagemSelecionada >=0) 
        {
            Conexao_Embalagem ce = new Conexao_Embalagem();
            Embalagem embalagem = ce.listar().get(embalagemSelecionada);
            if (JOptionPane.showConfirmDialog( this, "Deseja realmente excluir essa embalagem?") == JOptionPane.YES_OPTION) 
            {
              ce.excluir(embalagem);
              getTabelaEmbalagem();
              JOptionPane.showMessageDialog(null, "Embalagem excluída com sucesso!");
            } 
            
            else 
            {
                JOptionPane.showMessageDialog(null, "Selecione uma embalagem para excluir");
            }
        }
    }//GEN-LAST:event_btnExcluirEmbalagemActionPerformed

    private void btnAlterarEmbalagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarEmbalagemActionPerformed
        Conexao_Embalagem conexao_Embalagem = new Conexao_Embalagem();
        
        
       
        conexao_Embalagem.alterar(embalagem);
        getTabelaEmbalagem();
        
        JOptionPane.showMessageDialog(null, "Embalagem alterada com sucesso!");
    }//GEN-LAST:event_btnAlterarEmbalagemActionPerformed

    private void btnLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCamposActionPerformed
        tfdDescricaoEmbalagem.setText("");
        tfdComprimentoEmbalagem.setText("");
        tfdLarguraEmbalagem.setText("");
        tfdAlturaEmbalagem.setText("");
    }//GEN-LAST:event_btnLimparCamposActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogEmbalagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogEmbalagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogEmbalagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogEmbalagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogEmbalagem dialog = new DialogEmbalagem(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    public void getTabelaEmbalagem() {
        Conexao_Embalagem conexao_Embalagem = new Conexao_Embalagem();
        Vector cabecalho = new Vector();
        Vector linhas = new Vector();
        
        cabecalho.add("Descrição");
        cabecalho.add("Comprimento");
        cabecalho.add("Largura");
        cabecalho.add("Altura");
        
        for (int i = 0; i < conexao_Embalagem.listar().size(); i++) 
        {
            Vector colunas = new Vector();
            colunas.add((conexao_Embalagem.listar().get(i).getDescricao()));
            colunas.add(conexao_Embalagem.listar().get(i).getComprimento());
            colunas.add((conexao_Embalagem.listar().get(i).getLargura()));
            colunas.add((conexao_Embalagem.listar().get(i).getAltura()));

            linhas.add(new Vector(colunas));
        }

        tblListaEmbalagens.setModel(new DefaultTableModel(linhas, cabecalho));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarEmbalagem;
    private javax.swing.JButton btnBuscarEmbalagem;
    private javax.swing.JButton btnExcluirEmbalagem;
    private javax.swing.JButton btnIncluirEmbalagem;
    private javax.swing.JButton btnLimparCampos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListaEmbalagens;
    private javax.swing.JTextField tfdAlturaEmbalagem;
    private javax.swing.JTextField tfdBuscarEmbalagem;
    private javax.swing.JTextField tfdComprimentoEmbalagem;
    private javax.swing.JTextField tfdDescricaoEmbalagem;
    private javax.swing.JTextField tfdLarguraEmbalagem;
    // End of variables declaration//GEN-END:variables
}
