/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.Conexao_Embalagem;
import entities.Embalagem;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luciano
 */
public class DialogEmbalagem extends javax.swing.JDialog {

    /**
     * Creates new form DialogEmbalagem
     */
    public DialogEmbalagem(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();        
        this.setResizable(false);
        
        getTabelaEmbalagem();
    }
    
    Embalagem embalagem;
    DialogAlterarEmbalagem dialogAlterarEmbalagem;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpEmbalagem = new javax.swing.JPanel();
        jpInferior = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jpCentro = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfdDescricaoEmbalagem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaEmbalagens = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        btnIncluirEmbalagem = new javax.swing.JButton();
        tfdBuscarEmbalagem = new javax.swing.JTextField();
        btnBuscarEmbalagem = new javax.swing.JButton();
        btnExcluirEmbalagem = new javax.swing.JButton();
        btnAlterarEmbalagem = new javax.swing.JButton();
        btnLimparCampos = new javax.swing.JButton();
        tfdLarguraEmbalagem = new javax.swing.JTextField();
        tfdAlturaEmbalagem = new javax.swing.JTextField();
        tfdComprimentoEmbalagem = new javax.swing.JTextField();
        jpSuperior = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(950, 638));
        setResizable(false);

        jpEmbalagem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpInferior.setForeground(new java.awt.Color(0, 0, 140));
        jpInferior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 0, 140));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("© ECOMMERCE REGISTER SOLUTIONS - TODOS OS DIREITOS RESERVADOS © ");
        jPanel4.add(jLabel2, java.awt.BorderLayout.CENTER);

        jpInferior.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 14));

        jpEmbalagem.add(jpInferior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 585, 950, -1));

        jpCentro.setBackground(new java.awt.Color(255, 255, 255));
        jpCentro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 140));
        jLabel5.setText("LARGURA");
        jpCentro.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 140));
        jLabel6.setText("COMPRIMENTO");
        jpCentro.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 140));
        jLabel7.setText("ALTURA");
        jpCentro.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        tfdDescricaoEmbalagem.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        tfdDescricaoEmbalagem.setForeground(new java.awt.Color(0, 0, 140));
        tfdDescricaoEmbalagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdDescricaoEmbalagemActionPerformed(evt);
            }
        });
        jpCentro.add(tfdDescricaoEmbalagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 109, 210, -1));

        tblListaEmbalagens.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        tblListaEmbalagens.setForeground(new java.awt.Color(0, 0, 140));
        tblListaEmbalagens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", ""},
                {"", null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Descrição", "Comprimento", "Largura", "Altura"
            }
        ));
        jScrollPane1.setViewportView(tblListaEmbalagens);

        jpCentro.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 590, 380));

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 140));
        jLabel8.setText("DESCRIÇÃO");
        jpCentro.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 110, -1, 20));

        btnIncluirEmbalagem.setBackground(new java.awt.Color(0, 0, 140));
        btnIncluirEmbalagem.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnIncluirEmbalagem.setForeground(new java.awt.Color(255, 255, 255));
        btnIncluirEmbalagem.setText("Incluir Embalagem");
        btnIncluirEmbalagem.setBorder(null);
        btnIncluirEmbalagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirEmbalagemActionPerformed(evt);
            }
        });
        jpCentro.add(btnIncluirEmbalagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 319, -1, 27));

        tfdBuscarEmbalagem.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        tfdBuscarEmbalagem.setForeground(new java.awt.Color(0, 0, 140));
        tfdBuscarEmbalagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdBuscarEmbalagemActionPerformed(evt);
            }
        });
        jpCentro.add(tfdBuscarEmbalagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 280, 30));

        btnBuscarEmbalagem.setBackground(new java.awt.Color(0, 0, 140));
        btnBuscarEmbalagem.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnBuscarEmbalagem.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarEmbalagem.setText("Buscar Embalagens");
        btnBuscarEmbalagem.setBorder(null);
        btnBuscarEmbalagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEmbalagemActionPerformed(evt);
            }
        });
        jpCentro.add(btnBuscarEmbalagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 150, 30));

        btnExcluirEmbalagem.setBackground(new java.awt.Color(0, 0, 140));
        btnExcluirEmbalagem.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnExcluirEmbalagem.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluirEmbalagem.setText("Excluir Embalagem");
        btnExcluirEmbalagem.setBorder(null);
        btnExcluirEmbalagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirEmbalagemActionPerformed(evt);
            }
        });
        jpCentro.add(btnExcluirEmbalagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, 143, 27));

        btnAlterarEmbalagem.setBackground(new java.awt.Color(0, 0, 140));
        btnAlterarEmbalagem.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnAlterarEmbalagem.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterarEmbalagem.setText("Alterar Embalagem");
        btnAlterarEmbalagem.setBorder(null);
        btnAlterarEmbalagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarEmbalagemActionPerformed(evt);
            }
        });
        jpCentro.add(btnAlterarEmbalagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 139, 27));

        btnLimparCampos.setBackground(new java.awt.Color(0, 0, 140));
        btnLimparCampos.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnLimparCampos.setForeground(new java.awt.Color(255, 255, 255));
        btnLimparCampos.setText("Limpar Campos");
        btnLimparCampos.setBorder(null);
        btnLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCamposActionPerformed(evt);
            }
        });
        jpCentro.add(btnLimparCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 352, 129, 27));

        tfdLarguraEmbalagem.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        tfdLarguraEmbalagem.setForeground(new java.awt.Color(0, 0, 140));
        tfdLarguraEmbalagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdLarguraEmbalagemActionPerformed(evt);
            }
        });
        jpCentro.add(tfdLarguraEmbalagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 187, 210, -1));

        tfdAlturaEmbalagem.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        tfdAlturaEmbalagem.setForeground(new java.awt.Color(0, 0, 140));
        tfdAlturaEmbalagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdAlturaEmbalagemActionPerformed(evt);
            }
        });
        jpCentro.add(tfdAlturaEmbalagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 227, 210, -1));

        tfdComprimentoEmbalagem.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        tfdComprimentoEmbalagem.setForeground(new java.awt.Color(0, 0, 140));
        tfdComprimentoEmbalagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdComprimentoEmbalagemActionPerformed(evt);
            }
        });
        jpCentro.add(tfdComprimentoEmbalagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 147, 210, -1));

        jpEmbalagem.add(jpCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 950, 520));

        jpSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 0, 140));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Logo-trans-Pequeno.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(865, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpSuperior.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 70));

        jpEmbalagem.add(jpSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jpEmbalagem, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfdDescricaoEmbalagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdDescricaoEmbalagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdDescricaoEmbalagemActionPerformed

    private void btnIncluirEmbalagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirEmbalagemActionPerformed
        Conexao_Embalagem conexao_Embalagem = new Conexao_Embalagem();
        
        embalagem = new Embalagem();
        
        embalagem.setDescricao(tfdDescricaoEmbalagem.getText());
        embalagem.setComprimento(Double.parseDouble(tfdComprimentoEmbalagem.getText()));
        embalagem.setLargura(Double.parseDouble(tfdDescricaoEmbalagem.getText()));
        embalagem.setAltura(Double.parseDouble(tfdAlturaEmbalagem.getText()));
        
        conexao_Embalagem.inserir(embalagem);
        getTabelaEmbalagem();;
        
        JOptionPane.showMessageDialog(null, "Embalagem cadastrada com sucesso!");
        
    }//GEN-LAST:event_btnIncluirEmbalagemActionPerformed

    private void tfdBuscarEmbalagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdBuscarEmbalagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdBuscarEmbalagemActionPerformed

    private void btnBuscarEmbalagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEmbalagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarEmbalagemActionPerformed

    private void btnExcluirEmbalagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirEmbalagemActionPerformed
        Conexao_Embalagem conexao_Embalagem = new Conexao_Embalagem();
        
        int embalagemSelecionada = tblListaEmbalagens.getSelectedRow();
        
        if (embalagemSelecionada >=0) 
        {
            Conexao_Embalagem ce = new Conexao_Embalagem();
            Embalagem embalagem = ce.listar().get(embalagemSelecionada);
            if (JOptionPane.showConfirmDialog( this, "Deseja realmente excluir essa embalagem?") == JOptionPane.YES_OPTION) 
            {
              ce.excluir(embalagem);
              getTabelaEmbalagem();
              JOptionPane.showMessageDialog(null, "Embalagem excluída com sucesso!");
            } 
            
            else 
            {
                JOptionPane.showMessageDialog(null, "Selecione uma embalagem para excluir");
            }
        }
    }//GEN-LAST:event_btnExcluirEmbalagemActionPerformed

    private void btnAlterarEmbalagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarEmbalagemActionPerformed
        Conexao_Embalagem conexao_Embalagem = new Conexao_Embalagem();
        
        
       
        conexao_Embalagem.alterar(embalagem);
        getTabelaEmbalagem();
        
        JOptionPane.showMessageDialog(null, "Embalagem alterada com sucesso!");
    }//GEN-LAST:event_btnAlterarEmbalagemActionPerformed

    private void btnLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCamposActionPerformed
        tfdDescricaoEmbalagem.setText("");
        tfdComprimentoEmbalagem.setText("");
        tfdDescricaoEmbalagem.setText("");
        tfdAlturaEmbalagem.setText("");
    }//GEN-LAST:event_btnLimparCamposActionPerformed

    private void tfdLarguraEmbalagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdLarguraEmbalagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdLarguraEmbalagemActionPerformed

    private void tfdAlturaEmbalagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdAlturaEmbalagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdAlturaEmbalagemActionPerformed

    private void tfdComprimentoEmbalagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdComprimentoEmbalagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdComprimentoEmbalagemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogEmbalagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogEmbalagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogEmbalagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogEmbalagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogEmbalagem dialog = new DialogEmbalagem(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    public void getTabelaEmbalagem() {
        Conexao_Embalagem conexao_Embalagem = new Conexao_Embalagem();
        Vector cabecalho = new Vector();
        Vector linhas = new Vector();
        
        cabecalho.add("Descrição");
        cabecalho.add("Comprimento");
        cabecalho.add("Largura");
        cabecalho.add("Altura");
        
        for (int i = 0; i < conexao_Embalagem.listar().size(); i++) 
        {
            Vector colunas = new Vector();
            colunas.add((conexao_Embalagem.listar().get(i).getDescricao()));
            colunas.add(conexao_Embalagem.listar().get(i).getComprimento());
            colunas.add((conexao_Embalagem.listar().get(i).getLargura()));
            colunas.add((conexao_Embalagem.listar().get(i).getAltura()));

            linhas.add(new Vector(colunas));
        }

        tblListaEmbalagens.setModel(new DefaultTableModel(linhas, cabecalho));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarEmbalagem;
    private javax.swing.JButton btnBuscarEmbalagem;
    private javax.swing.JButton btnExcluirEmbalagem;
    private javax.swing.JButton btnIncluirEmbalagem;
    private javax.swing.JButton btnLimparCampos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpCentro;
    private javax.swing.JPanel jpEmbalagem;
    private javax.swing.JPanel jpInferior;
    private javax.swing.JPanel jpSuperior;
    private javax.swing.JTable tblListaEmbalagens;
    private javax.swing.JTextField tfdAlturaEmbalagem;
    private javax.swing.JTextField tfdBuscarEmbalagem;
    private javax.swing.JTextField tfdComprimentoEmbalagem;
    private javax.swing.JTextField tfdDescricaoEmbalagem;
    private javax.swing.JTextField tfdLarguraEmbalagem;
    // End of variables declaration//GEN-END:variables
}
