/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JFrame;

/**
 *
 * @author Luciano
 */
public class TelaGeral5 extends javax.swing.JFrame {

    /**
     * Creates new form TelaGeral5
     */
    public TelaGeral5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblProdutos = new javax.swing.JLabel();
        lblIconeProduto = new javax.swing.JLabel();
        lblRelatorios = new javax.swing.JLabel();
        lblIconeEntrada = new javax.swing.JLabel();
        lblEmbalagens = new javax.swing.JLabel();
        lblIconeEmbalagens = new javax.swing.JLabel();
        lblEntrada = new javax.swing.JLabel();
        lblSaida = new javax.swing.JLabel();
        lblIconeSaida = new javax.swing.JLabel();
        lblIconeRelatorios = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblProdutos.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lblProdutos.setForeground(new java.awt.Color(0, 102, 204));
        lblProdutos.setText("PRODUTOS");
        jPanel1.add(lblProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        lblIconeProduto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblIconeProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/product.png"))); // NOI18N
        lblIconeProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconeProdutoMouseClicked(evt);
            }
        });
        jPanel1.add(lblIconeProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, 92));

        lblRelatorios.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lblRelatorios.setForeground(new java.awt.Color(0, 102, 204));
        lblRelatorios.setText("RELATÓRIOS");
        jPanel1.add(lblRelatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));

        lblIconeEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/arrow_circle_right_icon_155798.png"))); // NOI18N
        jPanel1.add(lblIconeEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, -1, -1));

        lblEmbalagens.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lblEmbalagens.setForeground(new java.awt.Color(0, 102, 204));
        lblEmbalagens.setText("EMBALAGENS");
        jPanel1.add(lblEmbalagens, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 183, -1, -1));

        lblIconeEmbalagens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/box_icon_155728 (1).png"))); // NOI18N
        jPanel1.add(lblIconeEmbalagens, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        lblEntrada.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lblEntrada.setForeground(new java.awt.Color(0, 102, 204));
        lblEntrada.setText("ENTRADA");
        jPanel1.add(lblEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(601, 28, -1, -1));

        lblSaida.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lblSaida.setForeground(new java.awt.Color(0, 102, 204));
        lblSaida.setText("SAÍDA");
        jPanel1.add(lblSaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, -1, -1));

        lblIconeSaida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/arrow_circle_left_icon_155799.png"))); // NOI18N
        jPanel1.add(lblIconeSaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, -1, -1));

        lblIconeRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/log_icon_155172.png"))); // NOI18N
        jPanel1.add(lblIconeRelatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(0, 0, 140));

        jLabel1.setBackground(new java.awt.Color(0, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LOGO ERS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(695, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(0, 0, 140));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("© ECOMMERCE REGISTER SOLUTIONS - TODOS OS DIREITOS RESERVADOS © ");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, -1));

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblIconeProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconeProdutoMouseClicked
        JFrame produtoFrame = new JFrame();

        produtoFrame.setSize( 800, 800 );
        produtoFrame.setLocationRelativeTo( null );
    }//GEN-LAST:event_lblIconeProdutoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGeral5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGeral5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGeral5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGeral5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGeral5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblEmbalagens;
    private javax.swing.JLabel lblEntrada;
    private javax.swing.JLabel lblIconeEmbalagens;
    private javax.swing.JLabel lblIconeEntrada;
    private javax.swing.JLabel lblIconeProduto;
    private javax.swing.JLabel lblIconeRelatorios;
    private javax.swing.JLabel lblIconeSaida;
    private javax.swing.JLabel lblProdutos;
    private javax.swing.JLabel lblRelatorios;
    private javax.swing.JLabel lblSaida;
    // End of variables declaration//GEN-END:variables
}
